config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|nl|de/ do

    devise_for :shops
    devise_for :customers

    resources :welcome, only: [:index]

    root 'welcome#index'

    resources :contacts, only: [:new, :create]

    resources :shops do
      resources :sales
    end

    resources :customers

  end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :sales
  has_and_belongs_to_many :categories
# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  geocoded_by :full_address
  after_validation :geocode, if: :street_address_changed?

  #validates :name, presence: true
  #validates :street_address, presence: true
  #validates :city, presence: true
  #validates :postcode, presence: true
  #validates :country, presence: true
  #validates :phone, presence: true
  #validates :contact_email, presence: true
  #validates :category_ids, presence: true

  def full_address
    street_address + ' ' + postcode + ' ' + city
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_shop!, only: [:edit, :update, :destroy]
  before_action :find_shop

  def show
    @shop_coordinates = { lat: @shop.latitude, lng: @shop.longitude }
  end

  def edit
  end

  def update
    if current_shop == @shop
      @shop.update(shop_params)
      if @shop.valid?
        redirect_to shop_path(@shop), notice: "Your shop profile has been successfully updated"
      else
        render :edit
      end
    else
      redirect_to shop_path(@shop), notice: "You are not authorized to edit this page!"
    end
  end

  def destroy
    @shop.destroy
    redirect_to root_path, notice: "You have successfully deleted your shop profile"
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :street_address, :city, :postcode, :country, :opening, :closing, :phone, :contact_email, {:category_ids => []}, :picture)
  end

  def find_shop
   @shop = Shop.find(params[:id])
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/destroy.html.erb
<h1>Shops#destroy</h1>
<p>Find me in app/views/shops/destroy.html.erb</p>

app/views/shops/edit.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
     <div class="card hovercard">
        <div class="useravatar">
            <%= image_tag @shop.picture.url(:medium) %>
        </div>

<%= simple_form_for @shop do |f| %>
  <%= f.error_notification %>

        <div class="card-info"> <span class="card-title"><%= @shop.name %></span>

        </div>
    </div>
        <div class="well margin-left-left no-border">
       <div class="form-inputs">
            <%= f.input :name %>
            <%= f.association :categories, as: :check_boxes %>
            <%= f.input :street_address %>
            <%= f.input :city %>
            <%= f.input :postcode %>
            <%= f.input :country %>
            <%= f.input :phone %>
            <%= f.input :contact_email %>
            <%= f.input :picture %>
          </div>
            <div class ="sizee">
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
  </div>
  <%= link_to 'Back to shop profile', shop_path(@shop), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>

app/views/shops/show.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
    <div class="card hovercard">
        <div class="useravatar">
          <% if @shop.picture.present? %>
            <%= image_tag @shop.picture.url(:thumb) %>
          <% else %>
            <%= image_tag ("GetNGo1.png") %>
          <% end %>
        </div>
        <div class="card-info"> <span class="card-title"><%= @shop.name %></span>

        </div>
      <div class="tab-content">
        <strong>Categories:</strong>
        <ul class="list-unstyled">
          <% @shop.categories.each do |category| %>
          <li><%= category.name %></li>
          <% end %>
        </ul>
        <strong>Street address:</strong> <%= @shop.street_address %><br>
        <strong>City:</strong> <%= @shop.city %><br>
        <strong>Postcode:</strong> <%= @shop.postcode %><br>
        <strong>Country:</strong> <%= @shop.country %><br>
        <strong>Phone:</strong> <%= @shop.phone %><br>
        <strong>Contact email:</strong> <%= @shop.contact_email %><br>
        <%= image_tag "//maps.googleapis.com/maps/api/staticmap?size=400x300&markers=icon:path/to/image.png%257C996600%7C#{@shop.full_address}" %><br>

<% if shop_signed_in? %>
<%= link_to 'Edit your shop details', edit_shop_path(@shop), class: "btn btn-primary" %>
<%= link_to 'Add a new sale', new_shop_sale_path(@shop), class: "btn btn-primary" %>
<% end %>
        </div>
    </div>
    </div>
  </div>
  </div>
</div>