config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|nl|de/ do

    devise_for :shops
    devise_for :customers

    resources :welcome, only: [:index]

    root 'welcome#index'

    resources :contacts, only: [:new, :create]

    resources :shops do
      resources :sales
    end

    resources :customers

  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="flashy">
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  </div>
<% end %>
<% if alert %>
<div class="flashy">
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Get'N'Go 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="https://twitter.com/GetnGoflash"><i class="fa fa-twitter"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top <%= "navbar-opaque" if customer_signed_in? || shop_signed_in? %>">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <%= link_to image_tag("GetNGo1.png", :alt => "image", width:"130", class: "navbar-brand page-scroll"), root_path %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                <% if customer_signed_in? %>
                  <li><a class="page-scroll" href="/customers">Sales near me</a></li>
                  <li class="dropdown">
                      <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Profile
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="drop2">
                      <% if customer_signed_in? %>
                        <li><%= link_to "View profile", customer_path(current_customer) %></li>
                      <% else %>
                        <li><%= link_to "View profile", shop_path(current_shop) %></li>
                      <% end %>
                        <li><%= link_to destroy_customer_session_path || destroy_shop_session_path, method: :delete do %>
                        <%= t ".sign_out", default: "Log out" %></li>
                        <% end %>
                      </ul>
                    </li>
                <% elsif shop_signed_in? %>
                  <li><%= link_to 'My active sales', shop_sales_path(current_shop), class: "page-scroll" %></li>
                  <li class="dropdown">
                      <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Profile
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="drop2">
                      <% if customer_signed_in? %>
                        <li><%= link_to "View profile", customer_path(current_customer) %></li>
                      <% else %>
                        <li><%= link_to "View profile", shop_path(current_shop) %></li>
                      <% end %>
                        <li><%= link_to destroy_customer_session_path || destroy_shop_session_path, method: :delete do %>
                        <%= t ".sign_out", default: "Log out" %></li>
                        <% end %>
                      </ul>
                    </li>
                <% else %>
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Team</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li class="dropdown">
                      <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Sign up
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="drop2">
                        <li><%= link_to "Customer", new_customer_registration_path %></li>
                        <li><%= link_to "Shop", new_shop_registration_path %></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Login
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="drop2">
                        <li><%= link_to "Customer", new_customer_session_path %></li>
                        <li><%= link_to "Shop", new_shop_session_path %></li>
                      </ul>
                    </li>
                  </ul>
                <% end %>
                    </div><!-- /.navbar-collapse -->
              </div><!-- /.navbar-collapse -->
    </nav>