config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|nl|de/ do

    devise_for :shops
    devise_for :customers

    resources :welcome, only: [:index]

    root 'welcome#index'

    resources :contacts, only: [:new, :create]

    resources :shops do
      resources :sales
    end

    resources :customers

  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_and_belongs_to_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :picture,
  styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
  content_type: /\Aimage\/.*\z/

  #validates :first_name, presence: true
  #validates :family_name, presence: true
  #validates :birth_year, presence: true
  #validates :gender, presence: true
  #validates :base_location, presence: true
  #validates :category_ids, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :find_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customer = current_customer
    @categories = Category.all
    @search = params.fetch(:query, {})
    @shops = Shop.near(@search.fetch(:base_location, @customer.base_location), 35)
    @sales = Sale.where(shop_id: @shops.map(&:id), category: @search.fetch(:category, @customer.categories)).active_sales

    shop_with_sales = Shop.where(id: @sales.map(&:shop_id))

    @markers = Gmaps4rails.build_markers(shop_with_sales) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow render_to_string partial: "customers/card_map", locals: { shop: shop, sales: @sales.select { |s| s.shop == shop } }
    end
  end

  def show
    if current_customer == @customer
      customer_path(@customer)
    else
      redirect_to :root, notice: "You are not authorized to view other people's profiles!"
    end
  end

  def edit
  end

  def update
    if current_customer == @customer
      @customer.update(customer_params)
        if @customer.valid?
          redirect_to customer_path(@customer), notice: "Your customer profile has been successfully updated"
        else
          render :edit
        end
    else
      redirect_to customer_path(@customer), notice: "You are not authorized to edit this page!"
    end
  end

  def destroy
    @customer.destroy
    redirect_to root_path, notice: "You have successfully deleted your customer profile"
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :family_name, :birth_year, :gender, :base_location, :picture, {:category_ids => []})
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_card_map.html.erb
<div class="card-map-container">
        <div class="card-map">
        <h1><%= shop.name %></h1>
        <h4><%= shop.street_address %></h4>
          <%# if shop.picture.present? %>
          <%# else %>
          <%#= image_tag("GetNGo1.png", width: '35%') %>
          <%# end %>

          <% sales.each do |sale| %>
          <p><strong>Product in sale: </strong><%= sale.product_name %> <strong>for</strong> <%= sale.price %> € <strong>Terms:</strong> <%= sale.terms %></p>
        <%= link_to 'View sale details', shop_sale_path(sale.shop, sale), class: "btn btn-primary" %>
        <%= link_to 'Get map directions', "//maps.google.com/maps?daddr=#{shop.full_address}", target: '_blank', class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

app/views/customers/_card_product.html.erb
 <div class="card-product-container">

  <%= link_to shop_sale_path(sale.shop, sale) do %>
    <div class="card-product">
     <% if sale.picture.present? %>
          <% image = image_url sale.picture.url %>
        <% else %>
          <% image = image_url ("GetNGo1.png") %>
        <% end %>
      <div class="card-product-thumbnail" style="background-image: url('<%= image %>')" >

      </div>

      <div class='card-product-shop-name'>
        <%= sale.shop.name %>
        <div class='card-product-terms'><%= sale.terms %></div>

      </div>
      <div class='card-product-sentence'>
        Product in sale: <span class='card-product-name'><%= sale.product_name %></span> for <span class='card-product-price'><%= sale.price %>€</span>
      </div>
      <div class="card-product-footer">
        <div class='card-product-ending'>Sale ends at:
          <%= sale.ending.strftime('%H:%M:%S') %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/_search_bar.html.erb
<%= form_tag customers_path, method: :get do %>
  <div class="welll no-margin-bottom">
  <h4><%= label_tag 'Enter your search location:   ' %>  <%= text_field_tag 'query[base_location]', @search[:base_location], :value => @customer.base_location %>
    </h4>

    </div>
    <div class="welll no-margin-bottom">
    <% counter = 0 %>
       <div> <%= label_tag 'Choose a category:' %></div>
      <% @categories.each do |category| %>
        <% counter += 1 %>
        <div class="category-list">
          <%= check_box_tag 'query[category][]', category.id, @customer.category_ids.include?(category.id) ? true : false %>

          <% if counter == 3 %>
            <%= category.name %><br>
          <% elsif counter == 6 %>
            <%= category.name %><br>
          <% else %>
            <%= category.name %>
        <% end %>
        </div>
      <% end %><br>

    <% end %>
    <div class="btn-search-sale"><%= submit_tag 'Find my sale', class: "btn btn-primary-margin" %></div>
  </div>

app/views/customers/edit.html.erb
<div class="pickpick">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
     <div class="card hovercard">
        <div class="useravatar">
            <% if @customer.picture.present? %>
              <%= image_tag @customer.picture.url(:thumb) %>
            <% else %>
              <%= image_tag ("GetNGo1.png") %>
            <% end %>
        </div>
        <div class="card-info"> <span class="card-title"><%= @customer.first_name %></span>

<div class="row">

<h1>Edit your profile</h1>

<%= simple_form_for @customer do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left">
      <div class="card-block shadowed-box text-center">
        <div class= "sizee">
          <div class="form-inputs">
            <%= f.input :first_name %>
            <%= f.input :family_name %>
            <%= f.input :birth_year %>
            <%= f.input :gender, as: :check_boxes, collection: ['Male', 'Female'] %>
            <%= f.input :base_location %>
            <%= f.association :categories, as: :check_boxes, label: "Categories of interest:"%>
            <%= f.input :picture %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class ="sizee">
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>
    </div>
  </div>
    </div>
  </div>
</div>
</div>

<% content_for(:after_js) do %>
 <%= javascript_tag do %>
   $(document).on('ready', function() {

       function initializeAutocomplete(id) {
         var element = document.getElementById(id);
         if (element) {
           var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
           //google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
         }
       }
        initializeAutocomplete("customer_base_location")
     });
 <% end %>
<% end %>

app/views/customers/index.html.erb
  <div class="marginleft">
<div class="site-container">
  <div class="sidebar">
  <div class="search-product-container">
  <%= render partial: 'search_bar' %>
  </div>
    <% @sales.each do |sale| %>
    <%= render partial: "card_product", locals: { sale: sale } %>
    <% end %>
  </div>
  <div class="map-container">
    <div id="map" class="thumbnail" style="width: 100%; height: 100%;"></div>
  </div>
</div>
</div>

<% content_for(:after_js) do %>
 <script>
   $(document).ready(function() {

   var myStyle = [{"featureType":"all","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"simplified"},{"color":"#5b6571"},{"lightness":"35"}]},{"featureType":"administrative.neighborhood","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"landscape","elementType":"all","stylers":[{"visibility":"on"},{"color":"#f3f4f4"}]},{"featureType":"landscape.man_made","elementType":"geometry","stylers":[{"weight":0.9},{"visibility":"off"}]},{"featureType":"poi.park","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#83cead"}]},{"featureType":"road","elementType":"all","stylers":[{"visibility":"on"},{"color":"#ffffff"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"on"},{"color":"#fee379"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road.highway.controlled_access","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road.arterial","elementType":"all","stylers":[{"visibility":"simplified"},{"color":"#ffffff"}]},{"featureType":"road.arterial","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"color":"#7fc8ed"}]}]

     handler = Gmaps.build('Google');
     handler.buildMap({ internal: { id: 'map' } }, function(){
       markers = handler.addMarkers(<%= raw @markers.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();

       function initializeAutocomplete(id) {
         var element = document.getElementById(id);
         if (element) {
           var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
           //google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
         }
       }
        initializeAutocomplete("query_base_location")
     });
   })
 </script>
<% end %>

app/views/customers/show.html.erb
<div class="pickpick">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
     <div class="card hovercard">
        <div class="useravatar">
            <% if @customer.picture.present? %>
              <%= image_tag @customer.picture.url(:thumb) %>
            <% else %>
              <%= image_tag ("GetNGo1.png") %>
            <% end %>
        </div>
        <div class="card-info"> <span class="card-title"><%= @customer.first_name %></span>
<div class="row">
  <div class="well margin-left-right">
      <div class="tab-content">
            <h3>Base location:</h3> <%= @customer.base_location %><br>
            <h3>Categories of interest:</h3>
            <% @customer.categories.each do |category| %>
            <%= category.name %><br>
            <% end %>
        <% if customer_signed_in? %>
        <%= link_to 'Edit your profile details', edit_customer_path(@customer), class: "btn btn-primary" %>
        <% end %>
        </div>
    </div>
    </div>
  </div>
  </div>
  </div>
</div>