config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /fr|nl|de/ do

    devise_for :shops
    devise_for :customers

    resources :welcome, only: [:index]

    root 'welcome#index'

    resources :contacts, only: [:new, :create]

    resources :shops do
      resources :sales
    end

    resources :customers

  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :category
  belongs_to :shop
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  scope :active_sales, -> { where('ending > ?', Time.now) }

  validates :terms, presence: true
  validates :starting, presence: true
  validates :ending, presence: true
  validates :category_id, presence: true
  validates :shop_id, presence: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_shop!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_shop
  before_action :find_sale, only: [:show, :edit, :update, :destroy]

  def index
    @shop.sales.active_sales
  end

  def show
    @sale = Sale.find(params[:id])
    @shop_coordinates = { lat: @shop.latitude, lng: @shop.longitude }
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = @shop.sales.build(sale_params)
    if @sale.save
     redirect_to shop_sales_path(@shop), notice: 'The sale was successfully added'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sale.update(sale_params)
     redirect_to shop_sale_path(@shop, @sale), notice: 'The sale was successfully edited'
    else
      render :edit
    end
  end

  def destroy
    @sale.destroy
    redirect_to shop_sales_path(@shop), notice: "The sale was successfully deleted"
  end

  private

  def sale_params
    params.require(:sale).permit(:product_name, :product_description, :product_quantity, :picture, :price, :terms, :starting, :ending, :category_id, :shop_id)
  end

  def find_sale
    @sale = Sale.find(params[:id])
  end

   def find_shop
    @shop = Shop.find(params[:shop_id])
  end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/edit.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
    <div class="card hovercard">
<h1>Edit your sale</h1>
<%= simple_form_for [@shop, @sale] do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left">
      <div class="card-block shadowed-box text-center">
        <div class= "sizee">
          <div class="form-inputs">
            <%= f.association :category %>
            <%= f.input :product_name %>
            <%= f.input :product_description %>
            <%= f.input :product_quantity %>
            <%= f.input :picture %>
            <%= f.input :price, as: :currency %>
            <%= f.input :terms %>
            <%= f.input :starting, as: :time %>
            <%= f.input :ending, as: :time %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class ="sizee">
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
  <%= link_to 'Back to shop sales list', shop_sales_path(@shop), class: "btn btn-primary-margin2" %>
</div>
</div>
</div>
</div>
<% end %>_

app/views/sales/index.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
    <div class="card hovercard"><h1>Your shop currently has the following active sales</h1>

<% @shop.sales.each do |sale| %><br>
<strong>Sales category:</strong> <%= sale.category.name if sale.category %><br>
<strong>Product name:</strong> <%= sale.product_name %><br>
<strong>Price:</strong> <%= sale.price %> euros <br>
<strong>Sales terms & conditions:</strong> <%= sale.terms %><br>
<%= link_to 'View sale details', shop_sale_path(@shop, sale), class: "btn btn-primary" %>
<br><br>
<% end %>
<%= link_to 'Back to shop profile', shop_path(@shop), class: "btn btn-primary" %>

<% if shop_signed_in? %>
<%= link_to 'Add a new sale', new_shop_sale_path(@shop), class: "btn btn-primary" %>
</div>
</div>
</div>
</div>
<% end %>

app/views/sales/new.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
     <div class="card hovercard">
        <div class="useravatar">
            <%= image_tag @shop.picture.url(:thumb) %>
        </div>

<h1>Add a new sale</h1>

<%= simple_form_for [@shop, @sale] do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left">
      <div class="card-block shadowed-box text-center">
        <div class= "sizee">
          <div class="form-inputs">
            <%= f.association :category %>
            <%= f.input :product_name %>
            <%= f.input :product_description %>
            <%= f.input :product_quantity %>
            <%= f.input :picture %>
            <%= f.input :price, as: :currency %>
            <%= f.input :terms, label: 'Terms & conditions', placeholder: 'E.g. 20% off, private sales password' %>
            <%= f.input :starting, as: :time %>
            <%= f.input :ending, as: :time %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class ="sizee">
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
  <%= link_to 'Back to shop profile', shop_path(@shop), class: "btn btn-primary-margin2" %>
<% end %>
</div>
</div>
</div>
</div>

app/views/sales/show.html.erb
<body>
  <div class="wrap">
    <div class="single_deal">
      <div class="content" style="background-image: url(<%= raw @sale.picture.url %>) ">
        <div class="hover">
           <div class="description">
        <h2>Sales details</h2>
        <strong>Category: </strong> <%= @sale.category.name %><br>
        <strong>Product description: </strong> <%= @sale.product_description %><br>
        <strong>Product quantity: </strong> <%= @sale.product_quantity %><br>
        <strong>Terms & conditions: </strong> <%= @sale.terms %><br>

        <strong>Sale starts at: </strong> <%= @sale.starting.strftime("%H:%M") %><br>
        <strong>Sale ends at: </strong> <%= @sale.ending.strftime("%H:%M") %><br>

        <strong>Street address: </strong> <%= @shop.street_address %><br>
        <strong>City: </strong> <%= @shop.city %><br>
        <strong>Phone: </strong> <%= @shop.phone %><br>

          </div>
          <div class="call_to_action text-center">
            <% if shop_signed_in? && current_shop == @shop %>
<%= link_to 'Back to shop sales list', shop_sales_path(@shop), class: "btn btn-primary" %><br><br>
<%= link_to 'Edit sale details', edit_shop_sale_path(@shop, @sale), class: "btn btn-primary" %><br><br>
<%= link_to 'Delete this sale', shop_sale_path(@shop, @sale), method: :delete, data: {confirm: "Do you really wish to delete this sale?"}, class: "btn btn-primary" %>
<% else %>
<%= link_to 'Get map directions', "//maps.google.com/maps?daddr=#{@shop.full_address}", target: '_blank', class: "btn btn-primary" %><br><br><br>
<%= link_to 'Back to your sales list', :back, class: "btn btn-primary" %>
<% end %>
          </div>
        </div>

      </div>
      <div class="title">
        <h1 class="name"><%= @sale.product_name %></h1>
        <h1 class="price">€<%= @sale.price %></h1>
      </div>
    </div>

     <% if @sale.picture.present? %>
          <% image = image_url @sale.picture.url %>
        <% else %>
          <% image = image_url ("GetNGo1.png") %>
        <% end %>

app/views/sales/show3.html.erb
<div class="pickback">
      <div class="row">
<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2
 text-center padding-top">
    <div class="card hovercard">

        <div class="useravatar">
          <% if @shop.picture.present? %>
            <%= image_tag @shop.picture.url(:thumb) %>
          <% else %>
            <%= image_tag ("GetNGo1.png") %>
          <% end %>
        </div>
        <div class="card-info"> <span class="card-title"><%= @shop.name %></span>

    <div class="row">
        <div class="marginmargin"><strong>Sales details</strong></div>
        <strong>Category: </strong> <%= @sale.category.name %><br>
        <strong>Product name: </strong> <%= @sale.product_name %><br>
        <strong>Product description: </strong> <%= @sale.product_description %><br>
        <strong>Product quantity: </strong> <%= @sale.product_quantity %><br>
        <strong>Price (EUR): </strong><%= @sale.price %><br>
        <strong>Terms & conditions: </strong> <%= @sale.terms %><br>
      </div>
        <strong>Sale starts at: </strong> <%= @sale.starting.strftime("%H:%M") %><br>
        <strong>Sale ends at: </strong> <%= @sale.ending.strftime("%H:%M") %><br>
      </div>

        ________________________________________________________________
        <strong>Street address: </strong> <%= @shop.street_address %><br>
        <strong>City: </strong> <%= @shop.city %><br>
        <strong>Phone: </strong> <%= @shop.phone %><br>
        <strong>Contact email: </strong> <%= @shop.contact_email %><br>

    </div>

<% if @sale.picture.present? %>
  <%= image_tag @sale.picture.url(:thumb) %>
<% end %><br>

<% if shop_signed_in? && current_shop == @shop %>
<%= link_to 'Back to shop sales list', shop_sales_path(@shop), class: "btn btn-primary" %>
<%= link_to 'Edit sale details', edit_shop_sale_path(@shop, @sale), class: "btn btn-primary" %>
<%= link_to 'Delete this sale', shop_sale_path(@shop, @sale), method: :delete, data: {confirm: "Do you really wish to delete this sale?"}, class: "btn btn-primary" %>
<% else %>
<%= link_to 'Back to your sales list', :back, class: "btn btn-primary" %>
<% end %>
       </div>
      </div>
    </div>
        </div>
      </div>
    </div>
  </div>